### ISSUE TITLE
README.md amendments

### ISSUE THREAD

**Issue by BenGWeeks** [ministainer/Angular2SampleSPFx#1]
Couple of minor points:

There is no /example folder.
Should we be deploying the /temp/deploy folder, not the /dist folder to the CDN

**Comment by amrfouad22** [comment]
@webtechy  yes you should deploy /temp/deploy to the CDN you can use Office 365 public CDN check the below folder
https://dev.office.com/blogs/office-365-public-cdn-developer-preview-release
