### ISSUE TITLE
Error - typescript - node_modules\rxjs\Observable.d.ts(29,34): error TS1005: ')' expected

### ISSUE THREAD

**Issue by BenGWeeks** [ministainer/Angular2SampleSPFx#2]
Ran the following:

```
git clone https://github.com/ministainer/Angular2SampleSPFx.git
npm i
```

Set **./config/write-manifests.json** to:

https://[somecompany].sharepoint.com/sites/Development/SiteAssets/Angular2SampleSPFx/

Run the following:

`gulp build`

However, I received:

> Error - typescript - node_modules\rxjs\Observable.d.ts(29,34): error TS1005: ')' expected.

Followed by a bunch of similar issues.

In the package I see:

`"rxjs": "^5.0.0-beta.6",`

So I tried running:

```
npm install rxjs --save
npm install typescript --save-dev
```

Unfortunately that did not resolve the issue.

**tsd -v**
not installed

**tsc -v**
Version 1.8.34

**node -v**
v6.9.2

**ng --version**
angular-cli: 1.0.0-beta.25.5
node: 6.9.2
os: win32 x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5

**npm --version**
3.10.10

**Comment by amrfouad22** [comment]
The SPFx has been evolved since I created this sample and I didn't update the code base you can follow instructions on the release notes.
I've fixed it now
